[package]
name = "shadow_dhcpv6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "server"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
advmac = { version = "1.0.3", default-features = false, features = ["serde", "std"] }
compact_str = { version = "0.9.0", features = ["serde"] }
dhcproto = { git = "https://github.com/nocduro/dhcproto.git" }
ipnet = { version = "2.5", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"